version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build images
          command: |
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t hyperfiddle/imagemagick:$CIRCLE_SHA1 ./imagemagick
            docker push hyperfiddle/imagemagick:$CIRCLE_SHA1
