version: 2
jobs:
  awscli:
      docker:
        - image: docker:17.05.0-ce-git
      steps:
        - checkout
        - setup_remote_docker
        - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
        - run: docker build -t hyperfiddle/awscli:$CIRCLE_SHA1 ./awscli -t hyperfiddle/awscli:latest
        - run: docker push hyperfiddle/awscli

  imagemagick:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t hyperfiddle/imagemagick:$CIRCLE_SHA1 ./imagemagick -t hyperfiddle/imagemagick:latest
      - run: docker push hyperfiddle/imagemagick

  puppeteer:
      docker:
        - image: docker:17.05.0-ce-git
      steps:
        - checkout
        - setup_remote_docker
        - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
        - run: docker build -t hyperfiddle/puppeteer:$CIRCLE_SHA1 ./puppeteer -t hyperfiddle/puppeteer:latest
        - run: docker push hyperfiddle/puppeteer

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - awscli
      - imagemagick
      - puppeteer
